name: agenticir12
channels:
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2024.12.31=h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libstdcxx-ng=11.2.0=h1234567_1
  - libuuid=1.41.5=h5eee18b_0
  - ncurses=6.4=h6a678d5_0
  - openssl=3.0.15=h5eee18b_0
  - pip=24.2=py310h06a4308_0
  - python=3.10.16=he870216_1
  - readline=8.2=h5eee18b_0
  - setuptools=75.1.0=py310h06a4308_0
  - sqlite=3.45.3=h5eee18b_0
  - tk=8.6.14=h39e8969_0
  - wheel=0.44.0=py310h06a4308_0
  - xz=5.4.6=h5eee18b_1
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - absl-py==2.1.0
      - accelerate==1.3.0
      - addict==2.4.0
      - aiofiles==23.2.1
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.11.11
      - aiosignal==1.3.2
      - airportsdata==20250224
      - aliyun-python-sdk-core==2.16.0
      - aliyun-python-sdk-kms==2.16.5
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.8.0
      - argcomplete==3.5.3
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - argparse==1.4.0
      - args==0.1.0
      - array-record==0.6.0
      - arrow==1.3.0
      - astroid==3.3.8
      - asttokens==3.0.0
      - astunparse==1.6.3
      - async-lru==2.0.4
      - async-timeout==5.0.1
      - attrs==24.3.0
      - babel==2.16.0
      - backcall==0.2.0
      - basicsr==1.4.2
      - beautifulsoup4==4.12.3
      - bitsandbytes==0.45.0
      - bleach==6.2.0
      - boto==2.49.0
      - braceexpand==0.1.7
      - cachetools==5.5.1
      - certifi==2022.12.7
      - cffi==1.17.1
      - cfgv==3.4.0
      - charset-normalizer==2.1.1
      - chex==0.1.88
      - click==8.1.8
      - clint==0.5.1
      - cloudpickle==3.1.1
      - clu==0.0.12
      - colorama==0.4.6
      - comm==0.2.2
      - contextlib2==21.6.0
      - contourpy==1.3.1
      - crcmod==1.7
      - cryptography==44.0.0
      - cycler==0.12.1
      - dacite==1.8.1
      - dask==2025.1.0
      - dataclass-array==1.5.1
      - datasets==3.3.2
      - debugpy==1.8.12
      - decorator==5.1.1
      - defusedxml==0.7.1
      - diffusers==0.25.0
      - dill==0.3.8
      - diskcache==5.6.3
      - distlib==0.3.9
      - distro==1.9.0
      - dm-tree==0.1.8
      - docopt==0.6.2
      - docstring-parser==0.16
      - dominate==2.9.1
      - easydict==1.13
      - einops==0.8.0
      - einsum==0.3.0
      - etils==1.11.0
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - facexlib==0.3.0
      - fairscale==0.4.13
      - fastapi==0.115.8
      - fasteners==0.19
      - fastjsonschema==2.21.1
      - ffmpy==0.5.0
      - filelock==3.13.1
      - filterpy==1.4.5
      - flatbuffers==25.1.21
      - flax==0.10.2
      - fonttools==4.55.4
      - fortune==1.1.1
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - fsspec==2024.2.0
      - ftfy==6.3.1
      - future==1.0.0
      - gast==0.6.0
      - gcs-oauth2-boto-plugin==3.2
      - gdown==5.2.0
      - genson==1.3.0
      - gfpgan==1.3.8
      - google-apitools==0.5.32
      - google-auth==2.17.0
      - google-auth-httplib2==0.2.0
      - google-auth-oauthlib==1.2.1
      - google-pasta==0.2.0
      - google-reauth==0.1.1
      - googleapis-common-protos==1.66.0
      - gradio==5.15.0
      - gradio-client==1.7.0
      - grizzled-python==2.2.0
      - grpcio==1.69.0
      - h11==0.14.0
      - h5py==3.12.1
      - hpsv2==1.2.0
      - httpcore==1.0.7
      - httplib2==0.22.0
      - httpx==0.28.1
      - huggingface-hub==0.28.1
      - humanize==4.11.0
      - icecream==2.1.4
      - identify==2.6.6
      - idna==3.4
      - imageio==2.37.0
      - immutabledict==4.2.1
      - importlib-metadata==8.6.1
      - importlib-resources==6.5.2
      - iniconfig==2.0.0
      - interegular==0.3.3
      - ipykernel==6.29.5
      - ipython==8.12.3
      - ipywidgets==8.1.5
      - iso3166==2.1.1
      - isoduration==20.11.0
      - isort==5.13.2
      - jax==0.5.0
      - jaxlib==0.5.0
      - jedi==0.19.2
      - jinja2==3.1.3
      - jiter==0.8.2
      - jmespath==0.10.0
      - joblib==1.4.2
      - json5==0.10.0
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.11.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.4
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - jupyterlab-widgets==3.0.13
      - keras==3.8.0
      - kiwisolver==1.4.8
      - lark==1.2.2
      - lazy-loader==0.4
      - libclang==18.1.1
      - lightning-utilities==0.12.0
      - llvmlite==0.44.0
      - lmdb==1.6.2
      - locket==1.0.0
      - loralib==0.1.2
      - lpips==0.1.4
      - markdown==3.7
      - markdown-it-py==3.0.0
      - markupsafe==2.1.5
      - matplotlib==3.10.0
      - matplotlib-inline==0.1.7
      - maxim==1.0.0
      - mccabe==0.7.0
      - mdurl==0.1.2
      - mistune==3.1.0
      - ml-collections==1.0.0
      - ml-dtypes==0.4.1
      - model-index==0.1.11
      - monotonic==1.6
      - mpmath==1.3.0
      - msgpack==1.1.0
      - multidict==6.1.0
      - multiprocess==0.70.16
      - namex==0.0.8
      - natsort==8.4.0
      - nbclient==0.10.2
      - nbconvert==7.16.5
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - networkx==3.2.1
      - ninja==1.11.1.3
      - nodeenv==1.9.1
      - notebook==7.3.2
      - notebook-shim==0.2.4
      - numba==0.61.0
      - numpy==1.26.3
      - nvidia-cublas-cu12==12.1.3.1
      - nvidia-cuda-cupti-cu12==12.1.105
      - nvidia-cuda-nvrtc-cu12==12.1.105
      - nvidia-cuda-runtime-cu12==12.1.105
      - nvidia-cudnn-cu12==8.9.2.26
      - nvidia-cufft-cu12==11.0.2.54
      - nvidia-curand-cu12==10.3.2.106
      - nvidia-cusolver-cu12==11.4.5.107
      - nvidia-cusparse-cu12==12.1.0.106
      - nvidia-nccl-cu12==2.18.1
      - nvidia-nvjitlink-cu12==12.8.61
      - nvidia-nvtx-cu12==12.1.105
      - oauth2client==4.1.3
      - oauthlib==3.2.2
      - omegaconf==2.3.0
      - open-clip-torch==2.30.0
      - openai==1.59.9
      - openai-clip==1.0.1
      - opencv-python==4.11.0.86
      - opencv-python-headless==4.11.0.86
      - openexr==3.3.2
      - opt-einsum==3.4.0
      - optax==0.2.4
      - optree==0.14.0
      - orbax-checkpoint==0.11.0
      - ordered-set==4.1.0
      - orjson==3.10.15
      - outlines==0.2.1
      - outlines-core==0.1.26
      - overrides==7.7.0
      - packaging==24.2
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - partd==1.4.2
      - peft==0.10.0
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==10.2.0
      - pipreqs==0.5.0
      - pkgutil-resolve-name==1.3.10
      - platformdirs==4.3.6
      - plotly==5.24.1
      - pluggy==1.5.0
      - pre-commit==4.1.0
      - prometheus-client==0.21.1
      - promise==2.3
      - prompt-toolkit==3.0.50
      - propcache==0.2.1
      - protobuf==3.20.3
      - psutil==6.1.1
      - ptflops==0.7.4
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pyarrow==19.0.0
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.1
      - pycocotools==2.0.8
      - pycparser==2.22
      - pycryptodome==3.21.0
      - pydantic==2.10.5
      - pydantic-core==2.27.2
      - pydub==0.25.1
      - pygments==2.19.1
      - pyiqa==0.1.13
      - pylint==3.3.3
      - pyopenssl==25.0.0
      - pyparsing==3.2.1
      - pysocks==1.7.1
      - pytest==7.2.0
      - pytest-split==0.8.0
      - python-dateutil==2.9.0.post0
      - python-json-logger==3.2.1
      - python-multipart==0.0.20
      - pytorch-lightning==2.5.0.post0
      - pytorch-msssim==1.0.0
      - pytorch-ranger==0.1.1
      - pytz==2024.2
      - pyu2f==0.1.5
      - pywavelets==1.8.0
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - rawpy==0.24.0
      - referencing==0.36.1
      - regex==2024.11.6
      - requests==2.32.3
      - requests-oauthlib==2.0.0
      - retry-decorator==1.1.1
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rpds-py==0.22.3
      - rsa==4.7.2
      - ruff==0.9.5
      - safehttpx==0.1.6
      - safetensors==0.5.2
      - scikit-image==0.25.0
      - scikit-learn==1.6.1
      - scipy==1.15.1
      - semantic-version==2.10.0
      - send2trash==1.8.3
      - sentencepiece==0.2.0
      - shapely==2.0.6
      - shellingham==1.5.4
      - simple-parsing==0.1.7
      - simplejson==3.19.3
      - six==1.17.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - starlette==0.45.3
      - sympy==1.13.1
      - tabulate==0.9.0
      - tb-nightly==2.19.0a20250121
      - tenacity==9.0.0
      - tensorboard==2.18.0
      - tensorboard-data-server==0.7.2
      - tensorboard-plugin-wit==1.8.1
      - tensorboardx==2.6.2.2
      - tensorflow==2.18.0
      - tensorflow-addons==0.23.0
      - tensorflow-datasets==4.9.7
      - tensorflow-estimator==2.15.0
      - tensorflow-graphics==2021.12.3
      - tensorflow-io-gcs-filesystem==0.37.1
      - tensorflow-metadata==1.16.1
      - tensorflow-probability==0.25.0
      - tensorstore==0.1.71
      - termcolor==2.5.0
      - terminado==0.18.1
      - terminaltables==3.1.10
      - thop==0.1.1-2209072238
      - threadpoolctl==3.5.0
      - tifffile==2025.1.10
      - timm==1.0.14
      - tinycss2==1.4.0
      - tokenizers==0.21.0
      - toml==0.10.2
      - tomli==2.2.1
      - tomlkit==0.13.2
      - toolz==1.0.0
      - torch==2.1.2
      - torch-optimizer==0.3.0
      - torchaudio==2.1.2
      - torchmetrics==1.6.1
      - torchsde==0.2.6
      - torchstat==0.0.7
      - torchsummary==1.5.1
      - torchvision==0.16.2
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - trampoline==0.1.2
      - transformers==4.49.0
      - trimesh==4.6.0
      - triton==2.1.0
      - typeguard==2.13.3
      - typer==0.15.1
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - tzdata==2025.1
      - uri-template==1.3.0
      - urllib3==1.26.13
      - uvicorn==0.34.0
      - virtualenv==20.29.1
      - visu3d==1.5.3
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webdataset==0.2.111
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - websockets==12.0
      - werkzeug==3.1.3
      - widgetsnbextension==4.0.13
      - wrapt==1.17.2
      - xformers==0.0.23.post1
      - xxhash==3.5.0
      - yacs==0.1.8
      - yapf==0.43.0
      - yarg==0.1.9
      - yarl==1.18.3
      - zipp==3.21.0
