GPT:
  API_KEY: ""
  MODEL: "gpt-4-turbo"
  MAX_TOKENS: 3000
  TEMPERATURE: 0.0

LLAMA:
  API_KEY: ""
  MODEL: "llama3.1-405b"
  MAX_TOKENS: 3000
  TEMPERATURE: 0.0

AZUREGPT:
  API_KEY: ""
  MODEL: ""
  MAX_TOKENS: 3000
  TEMPERATURE: 0.0
  ENDPOINT: ""
  API_VERSION: ""