name: NAFNet-GoPro-width64_deblur
model_type: ImageRestorationModel
scale: 1
num_gpu: 1 # set num_gpu: 0 for cpu mode
manual_seed: 10

# dataset and data loader settings
datasets:
  test_1:
    name: test
    type: SingleImageDataset
    dataroot_lq: ~
    io_backend:
      type: disk

# network structures
network_g:
  type: NAFNetLocal
  width: 64
  enc_blk_nums: [1, 1, 1, 28]
  middle_blk_num: 1
  dec_blk_nums: [1, 1, 1, 1]


# path
path:
  pretrain_network_g: NAFNet-GoPro-width64.pth
  strict_load_g: true
  param_key_g: 'params_ema'
  resume_state: ~

# validation settings
val:
  save_img: true
  suffix: ~  # add suffix to saved images, if None, use exp name
  grids: false
