# general settings
name: HMA_X4
model_type: HMAModel
scale: 4
num_gpu: auto
manual_seed: 1234

datasets:
  test_1:
    name: test
    type: SingleImageDataset
    dataroot_lq: ~
    io_backend:
      type: disk

# network structures
network_g:
  type: HMANet
  upscale: 4
  in_chans: 3
  img_size: 64
  window_size: 16
  interval_size: 4
  img_range: 1.
  depths: [6, 6, 6, 6, 6, 6]
  embed_dim: 180
  num_heads: [6, 6, 6, 6, 6, 6]
  mlp_ratio: 2
  upsampler: 'pixelshuffle'
  resi_connection: '1conv'


# path
path:
  pretrain_network_g: HMA_SRx4_pretrain.pth
  strict_load_g: true
  param_key_g: 'params_ema'

# validation settings
val:
  save_img: true
  suffix: ~  # add suffix to saved images, if None, use exp name

# tile settings
tile:
  tile_size: 256
  tile_pad: 32