name: NAFSSR-L_4x
model_type: ImageRestorationModel
scale: 4
num_gpu: 1 # set num_gpu: 0 for cpu mode
manual_seed: 10

tile: # use the tile mode for limited GPU memory when testing.
  tile_size: 512 # the higher, the more utilized GPU memory and the less performance change against the full image. must be an integer multiple of the window size.
  tile_pad: 32 # overlapping between adjacency patches.must be an integer multiple of the window size.

# dataset and data loader settings
datasets:
  test_1:
    name: test
    type: SingleImageDataset
    dataroot_lq: ~
    io_backend:
      type: disk

# network structures
network_g:
  type: NAFSSR
  up_scale: 4
  width: 128
  num_blks: 128


# path
path:
  pretrain_network_g: NAFSSR-L_4x.pth
  strict_load_g: true
  param_key_g: 'params_ema'
  resume_state: ~

# validation settings
val:
  save_img: true
  suffix: ~  # add suffix to saved images, if None, use exp name
  grids: false
